language: node_js
node_js: 
  - 'node'
install:
  - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
  - unzip awscliv2.zip
  - sudo ./aws/install
  - npm install
script: 
  - npm test
before_deploy:
  - aws s3 rm s3://chain-agent.kmunton.dev --recursive
  - npm run build
deploy:
  provider: s3
  access_key_id: "$ACCESSKEYID"
  secret_access_key: "$SECRETACCESSKEY"
  bucket: "chain-agent.kmunton.dev"
  region: eu-west-2
  local_dir: build
  skip_cleanup: true
  on:
    branch: main
after_deploy:
  - aws cloudfront create-invalidation --distribution-id $DISTRIBUTIONID --paths "/*"
